# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8fe242f34aa664c0e821db9c47d23502fd62eb0d649225d2715554c202205b44c7bf7548ad60a115798fffe9ea37573c3a319fd141221ee4b9fbc00b78d715

test:
  secret_key_base: d0b4447b3407863999ad4dd2a538f2519cabcc29326d09f6fc37e24a276d2c2db454b9e17142cc7e9ae3c3d90a23c79a76a73d5978a1ad0d45982498282ba8d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
